language: generic
dist: trusty
sudo: required
python:
  - 2.7
os:
  - linux
  - osx
notifications:
  email: false
install: 
  - sudo pip install urllib3 pyopenssl ndg-httpsclient pyasn1
  - sudo pip install git+git://github.com/ansible/ansible.git@stable-2.2
script:
  - git config --global user.name "Test name"
  - git config --global user.email "test@localhost"
  
  # GitKraken
  - ./setup --tags=gitkraken

  # Elixir and Erlang
  - ./setup --tags=erlang,elixir
