language: generic
dist: trusty
sudo: required
python:
  - 2.7
os:
  - linux
  - osx

env:
  - ANSIBLE_TAGS=tools TEST_SCRIPT=tools
  - ANSIBLE_TAGS=erlang,elixir,golang,node TEST_SCRIPT=languages
  - ANSIBLE_TAGS=gitkraken,vscode,vagrant TEST_SCRIPT=development

notifications:
  email: false


before_install:
  # Cleanup existing NVM installation
  - unset NVM_CD_FLAGS
  - unset NVM_DIR
  - unset NVM_BIN
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then rm -rf /Users/travis/.nvm; fi
  - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then rm -rf /home/travis/.nvm; fi
  - rm -rf /etc/profile.d/travis-nvm.sh
  # Cleanup existing Kiex installation
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then rm -rf /Users/travis/.kiex; fi
  - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then rm -rf /home/travis/.kiex; fi
  - rm -rf /etc/profile.d/kiex.sh
  # Remove Erlang support
  - >
    if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then
      sudo apt-get remove erlang-base erlang erlang-base-hipe
      sudo apt-get autoremove
    fi

install:
  - sudo pip install urllib3 pyopenssl ndg-httpsclient pyasn1
  - sudo pip install git+git://github.com/ansible/ansible.git@stable-2.2

before_script:
  # https://github.com/travis-ci/travis-ci/issues/6307
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then rvm get head || true; fi

script:
  - git config --global user.name "Test name"
  - git config --global user.email "test@localhost"

  # Run init only
  - ./setup -n

  # Check syntax only
  - ./setup -q -s

  # Run playbooks with the selected tags only
  - ./setup -q -t $ANSIBLE_TAGS

  # Idempotence test
  - >
    ./setup -q -t $ANSIBLE_TAGS
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)

  - ./tests/$TEST_SCRIPT
