- hosts: localhost
  vars:
    - node_version: 6
    - local_home: "{{ lookup('env','HOME') }}"
    - golang_path: "Projects/golang"
    - is_ci: "{{ ansible_env.TRAVIS_JOB_ID is defined }}"
    - isnt_ci: "{{ ansible_env.TRAVIS_JOB_ID is not defined }}"
    - is_osx: "{{ ansible_os_family == 'Darwin' }}"
    - is_ubuntu: "{{ ansible_distribution == 'Ubuntu' }}"
    - is_ubuntu13_plus: "{{ is_ubuntu and ansible_distribution_version|int >= 13 }}"
    - is_ubuntu15_plus: "{{ is_ubuntu and ansible_distribution_version|int >= 15 }}"

  tasks:

    # essentials:
    - include: tasks/apt.yml
    #- include: tasks/homebrew.yml
    - include: tasks/core.yml
    #- include: tasks/dotfiles.yml

    # Install programming languages
    - include: tasks/python.yml
    - include: tasks/golang.yml
    - include: tasks/node.yml

    # Docker installs Kernel updates, install before other software
    - include: tasks/docker.yml

    # Install Vagrant and Virtualbox early as well
    - include: tasks/vagrant.yml
    - include: tasks/virtualbox.yml

    # specific stuff than can be commented out:
    - include: tasks/atom.yml
    - include: tasks/awscli.yml
    - include: tasks/google-cloud-sdk.yml
    - include: tasks/chrome.yml
    - include: tasks/dbeaver.yml
    # - include: tasks/diffmerge.yml
    # - include: tasks/dropbox.yml
    # - include: tasks/google-drive.yml
    # - include: tasks/intellij.yml
    # - include: tasks/ngrok.yml
    # - include: tasks/postgres.yml
    - include: tasks/playdeb.yml
    - include: tasks/pycharm.yml
    # - include: tasks/quicklook.yml
    # - include: tasks/ruby.yml
    # - include: tasks/skype.yml
    - include: tasks/slack.yml
      when: is_osx
    - include: tasks/scudcloud.yml
      when: is_ubuntu
    # - include: tasks/slate.yml
    - include: tasks/spotify.yml
    # - include: tasks/sublime-text.yml
    - include: tasks/telegram.yml
    - include: tasks/terminal.yml
    - include: tasks/visual-studio-code.yml
    - include: tasks/vlc.yml
    # - include: tasks/vpn.yml
    # - include: tasks/whatsapp.yml
  #roles:
  #  - caarlos0.java-dev
  #  - caarlos0.eclipse
