---

- name: Setup variables
  hosts: localhost
  tasks:
    - name: Set OS and environment facts
      set_fact:
        is_ci: "{{ ansible_env.TRAVIS_JOB_ID is defined }}"
        isnt_ci: "{{ ansible_env.TRAVIS_JOB_ID is not defined }}"
        is_osx: "{{ ansible_os_family == 'Darwin' }}"
        is_linux: "{{ ansible_system == 'Linux' }}"
        is_ubuntu: "{{ ansible_distribution == 'Ubuntu' }}"
      tags: always
    - name: Set Ubuntu version facts
      set_fact:
        is_ubuntu13_plus: "{{ is_ubuntu and ansible_distribution_version|int >= 13 }}"
        is_ubuntu15_plus: "{{ is_ubuntu and ansible_distribution_version|int >= 15 }}"
      tags: always

- name: Install essential tools and system packages
  hosts: localhost
  tasks:
    - include: tasks/ubuntu/apt.yml
      when: is_ubuntu
      tags:
      - apt
      - base
    - include: tasks/osx/homebrew.yml
      when: is_osx
      tags:
      - homebrew
      - base
    - include: tasks/common/core.yml
      tags:
      - tools
      - base
    - include: tasks/ubuntu/core.yml
      when: is_ubuntu
      tags:
      - tools
      - base
    - include: tasks/osx/core.yml
      when: is_osx
      tags:
      - tools
      - base
    - include: tasks/common/terminal.yml
      tags:
      - terminal
      - base
    - include: tasks/networking/ufw.yml
      when: is_ubuntu
      tags:
      - ufw
      - firewall

- name: Install programming languages
  hosts: localhost
  vars:
    - nodejs_version: 7.x
    - erlang_version: 19.2
  pre_tasks:
    # Installed Python before other languages
    - include: tasks/languages/python.yml
      tags:
      - python
      - languages
  roles:
    - role: nodesource.node
      when: is_ubuntu
      tags:
      - node
      - languages
    # The kbrebanov.erlang role fails if trying to run it on OS X
    - role: kbrebanov.erlang
      when: is_ubuntu
      tags:
      - elixir
      - erlang
      - languages
    - role: markosamuli.golang
      tags:
      - golang
      - languages
  tasks:
    - include: tasks/languages/node.yml
      when: is_osx
      tags:
      - node
      - languages
  post_tasks:
    # Elixir needs to be installed after Erlang on Ubuntu, Homebrew installs it automatically on OS X
    - include: tasks/languages/elixir.yml
      tags:
       - elixir
       - languages

- name: Install IDEs and other development tools
  hosts: localhost
  roles:
    - role: markosamuli.visual-studio-code
      tags:
      - visual-studio-code
      - vscode
      - development
  tasks:
    - include: tasks/development/docker.yml
      when: isnt_ci
      tags:
      - devops
      - development
    - include: tasks/development/vagrant.yml
      tags:
      - vagrant
      - development
    - include: tasks/development/virtualbox.yml
      when: isnt_ci
      tags:
      - virtualbox
      - development
    - include: tasks/development/atom.yml
      tags:
      - atom
      - development
    - include: tasks/development/gitkraken.yml
      tags:
      - gitkraken
      - development
    - include: tasks/development/pycharm.yml
      tags:
      - development
      - pycharm
    - include: tasks/development/dbeaver.yml
      tags:
      - database
      - development

- name: Install Cloud and DevOps tools
  hosts: localhost
  roles:
    - role: markosamuli.terraform
      tags:
      - terraform
      - devops
      - cloud
    - role: markosamuli.packer
      tags:
      - packer
      - devops
      - cloud
    - role: markosamuli.aws-tools
      tags:
      - aws
      - devops
      - cloud
  tasks:
    - include: tasks/cloud/google-cloud-sdk.yml
      tags:
      - gcloud
      - development
      - devops
      - cloud

- name: Install browsers, media players, messaging tools, games and other fun stuff
  hosts: localhost
  tasks:
    - include: tasks/browsers/chrome.yml
      tags:
      - chrome
      - browsers
    - include: tasks/browsers/firefox.yml
      tags:
      - firefox
      - browsers
    - include: tasks/media/spotify.yml
      tags:
      - spotify
      - media
    - include: tasks/media/vlc.yml
      tags:
      - vlc
      - media
    - include: tasks/messaging/slack.yml
      when: is_osx
      tags:
      - slack
      - messaging
    - include: tasks/messaging/scudcloud.yml
      when: is_ubuntu
      tags:
      - slack
      - messaging
    - include: tasks/messaging/telegram.yml
      tags:
      - telegram
      - messaging
    - include: tasks/messaging/corebird.yml
      when: is_ubuntu
      tags:
      - messaging
      - twitter
    - include: tasks/games/playdeb.yml
      tags:
      - games
    - include: tasks/networking/vpn.yml
      tags:
      - vpn
