---

# Ubuntu roles
- src: kbrebanov.erlang

# Shared roles
- src: https://github.com/markosamuli/ansible-visual-studio-code
  name: markosamuli.visual-studio-code
- src: https://github.com/markosamuli/ansible-terraform
  name: markosamuli.terraform
- src: https://github.com/markosamuli/ansible-packer
  name: markosamuli.packer
- src: https://github.com/markosamuli/ansible-aws-tools
  name: markosamuli.aws-tools
- src: https://github.com/markosamuli/ansible-nvm
  name: markosamuli.nvm
