- name: Ubuntu | Install DBeaver
  apt: deb=http://dbeaver.jkiss.org/files/dbeaver-ce_latest_amd64.deb
  when: is_ubuntu

- name: OS X | Install DBeaver
  homebrew_cask: name=dbeaver-community
  when: is_osx
