- name: Ubuntu | Add Docker repository key
  apt_key:
    id: "58118E89F3A912897C070ADBF76221572C52609D"
    keyserver: "hkp://p80.pool.sks-keyservers.net:80"
    state: present
  register: add_repository_key
  # ignore_errors: true
  when: is_ubuntu13_plus

- debug: var=add_repository_key

- name: Ubuntu | Add Docker repository
  apt_repository: repo='deb https://apt.dockerproject.org/repo ubuntu-{{ ansible_distribution_release }} main'
  when: is_ubuntu13_plus

- name: Ubuntu | Linux Kernel version
  shell: uname -r
  ignore_errors: yes
  register: uname_result
  when: is_ubuntu13_plus

- name: Ubuntu | Install linux-image-extra-* packages
  package: name="{{ item }}"
  with_items:
  - "linux-image-extra-{{ uname_result.stdout }}" 
  - "linux-image-extra-virtual"
  when: is_ubuntu13_plus

- name: Ubuntu | Install Docker
  package: name=docker-engine
  when: is_ubuntu13_plus

# TODO: waiting for docker for mac exit beta
- name: OS X | Install Docker for Mac
  homebrew_cask: name=docker
  when: is_osx
