---

- name: Set GOLANG projects path
  set_fact:
    local_home: "{{ lookup('env','HOME') }}"
    golang_path: "Projects/golang"

- name: Ubuntu | Add golang repository
  apt_repository: repo='ppa:ubuntu-lxc/lxd-stable'
  when: is_ubuntu

- name: Install Golang
  package: name=golang

- name: Create golang projects directory
  file:
    path: "{{ local_home }}/{{ golang_path }}"
    state: directory
    recurse: yes
  become: False  

- name: Test if $HOME/.zshrc exists
  stat: path="{{ local_home }}/.zshrc" 
  register: zshrc_stat
  become: False

- name: Add GOPATH to $HOME/.zshrc
  lineinfile: 
    dest: "{{ local_home }}/.zshrc" 
    line: "export GOPATH=$HOME/{{ golang_path }}"
  become: False
  when: zshrc_stat.stat.exists == True

- name: Add $GOPATH/bin to PATH in $HOME/.zshrc
  lineinfile: 
    dest: "{{ local_home }}/.zshrc" 
    line: "export PATH=$PATH:$GOPATH/bin"
  become: False
  when: zshrc_stat.stat.exists == True 