- name: Ubuntu | Add golang repository
  apt_repository: repo='ppa:ubuntu-lxc/lxd-stable'
  when: is_ubuntu
  tags: golang

- name: Install Golang
  package: name=golang
  tags: golang

- name: Create golang projects directory
  file:
    path: "{{ local_home }}/{{ golang_path }}"
    state: directory
    recurse: yes
  become: False  
  tags: golang

- stat: path="{{ local_home }}/.zshrc" 
  register: zshrc_stat
  become: False
  tags: golang

- name: Add GOPATH to $HOME/.zshrc
  lineinfile: 
    dest: "{{ local_home }}/.zshrc" 
    line: "export GOPATH=$HOME/{{ golang_path }}"
  become: False
  when: zshrc_stat.stat.exists == True
  tags: golang