- name: Ubuntu | Install Slack
  apt: deb=https://slack-ssb-updates.global.ssl.fastly.net/linux_releases/slack-1.1.5-amd64.deb
  when: is_ubuntu

- name: OS X | Install Slack
  homebrew_cask: name=slack
  when: is_osx
