- name: Ubuntu | Add SublimeText repository
  apt_repository: repo='ppa:webupd8team/sublime-text-3'
  when: is_ubuntu
- name: Ubuntu | Install SublimeText
  package: name=sublime-text-installer
  when: is_ubuntu

- name: OS X | Install SublimeText
  homebrew_cask: name=sublime-text
  when: is_osx
