- name: Ubuntu | Install OpenVPN stuff
  package: name={{ item }}
  with_items:
    - network-manager-openvpn
    - openvpn
  when: is_ubuntu
- name: OS X | Install Viscosity
  homebrew_cask: name=viscosity
  when: is_osx
