---

- name: Python | Install Python
  package:
    name: python

- name: Python | Install Python package installer
  package:
    name: python-pip

- name:  Python | Upgrade pip
  pip:
    name: pip
    state: latest

- name: Python | OS X | Install pyenv and pyenv-virtualenv
  package:
    name: '{{ item }}'
  with_items:
  - pyenv
  - pyenv-virtualenv
  when: is_osx
