---

- name: Ubuntu | Enable UFW
  ufw: state=enabled

- name: Ubuntu | Allow all outgoing traffic
  ufw: policy=allow direction=outgoing

- name: Ubuntu | Deny all incoming traffic
  ufw: policy=deny direction=incoming

- name: Ubuntu | Enable UFW logging
  ufw: logging=on

- name: Ubuntu | Install Gufw (GUI for UFW)
  package: name=gufw
