# TODO: simplify this once ansible 2.1 is out
- name: Ubuntu | Add Atom PPA
  apt_repository: repo='ppa:webupd8team/atom'
  when: is_ubuntu
- name: Ubuntu | Install Atom
  package: name=atom
  when: is_ubuntu

- name: OS X | Install Atom
  homebrew_cask: name=atom
  when: is_osx
