---

- name: Ubuntu | Docker | Add Docker repository key
  apt_key:
    id: "58118E89F3A912897C070ADBF76221572C52609D"
    keyserver: "hkp://p80.pool.sks-keyservers.net:80"
    state: present
  when: is_ubuntu13_plus

- name: Ubuntu | Docker | Add Docker repository
  apt_repository:
    repo: 'deb https://apt.dockerproject.org/repo ubuntu-{{ ansible_distribution_release }} main'
  when: is_ubuntu13_plus

- name: Ubuntu | Docker | Linux Kernel version
  shell: uname -r
  ignore_errors: yes
  register: uname_result
  when: is_ubuntu13_plus

- name: Ubuntu | Docker | Install linux-image-extra-* packages
  package:
    name: "{{ item }}"
  with_items:
  - "linux-image-extra-{{ uname_result.stdout }}"
  - "linux-image-extra-virtual"
  when: is_ubuntu13_plus

- name: Ubuntu | Docker | Install Docker Engine
  package:
    name: docker-engine
  when: is_ubuntu13_plus

# TODO: waiting for docker for mac exit beta
- name: OS X | Docker | Install Docker for Mac
  homebrew_cask:
    name: docker
  when: is_osx
