---

- name: Ubuntu | Update APT cache
  apt:
    update_cache: yes
    cache_valid_time: 3600
  when: isnt_ci

- name: Ubuntu | Add APT support for transport over HTTPS
  apt:
    name: '{{ item }}'
    state: present
  with_items:
   - apt-transport-https
   - ca-certificates
