---

- name: OS X | Update Homebrew
  homebrew:
    update_homebrew: yes
  when: isnt_ci

- name: OS X | Add Homebrew taps
  homebrew_tap:
    tap: "{{ item }}"
  with_items:
    - caskroom/cask
    - caskroom/fonts
    - caskroom/versions
